### ISSUE TITLE
This function is not monotone

### ISSUE THREAD

**Issue by Rustinante** [CS131-TA-team/UCLA_CS131_CodeHelp#2]
https://github.com/CS131-TA-team/UCLA_CS131_CodeHelp/blob/efa91366cfb3441ffe0992c68f078fcee675331c/OCaml/hw1/python_hint.py#L135

**Comment by PatriciaXiao** [comment]
Is there any explicit explanation on what do you mean by "not monotone"?

**Comment by Rustinante** [comment]
When `get_reachable_symbols` is being used as the `f` for computing the fixed point, after each application of `f` the `rules` in the return value becomes empty,  i.e., `f(x)` is not a superset of `x`.

**Comment by PatriciaXiao** [comment]
I think you can come to our office hours or ask on Piazza about this issue, I suspect that this is a misunderstanding of its usage. `len(rules) = 0` serves as part of the end condition. It is because I want to make it tail-recursive.

It should be working correctly. Its basic correctness is verified in the previous quarters.

Please feel free to come to our office hours for further questions on this piece of code if you are still interested!

**Comment by Rustinante** [comment]
I'm not a student. Just trying to do you a favor because there's a bug in your hint.

**Comment by JohnnyUrosevic** [comment]
He's right, the code does not work as intended and fails the given test cases in the assignment (specifically when you start with LValue).

**Comment by Rustinante** [comment]
@JohnnyUrosevic Please let Dr Eggert know too, thanks!
